server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
        route:
          - id: USER-SERVICE
            uri:
              lb://USER-SERVICE
            predicates:
              - Path=/auth/**, /users/**, /api/users/**, /
          - id: TASK-SERVICE
            uri:
              lb://TASK-SERVICE
            predicates:
              - Path=/tasks/**, /api/tasks/**
          - id: SUBMISSION-SERVICE
            uri:
              lb://SUBMISSION-SERVICE
            predicates:
              - Path=/submissions/**, /api/submissions/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
