server:
  port: 5002

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task_service_db
    username: root
    password: cdac
    driver-class-name: com.mysql.cj.jdbc.Driver

   